---
- name: Upload public SSH key to target hosts
  hosts: all
  become: yes
  gather_facts: false

  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  # Path to your public key

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Upload SSH public key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ ssh_public_key }}"

    - name: Set correct permissions on authorized_keys
      file:
        path: /home/ubuntu/.ssh/authorized_keys
        owner: ubuntu
        group: ubuntu
        mode: '0600'
